[build]
publish = "dist"
command = "npm install && npm run build"


[build.environment]
  NODE_VERSION = "22"
  # Force building the native binary on the Netlify runner
  NPM_CONFIG_BUILD_FROM_SOURCE = "better-sqlite3"
